# build_setup_exe.ps1
# ====================
# Compiles installer/setup_wizard.py into a single HandGalaxySetup.exe
# using PyInstaller.
#
# Run from the project root after setup.bat has been completed.
# Output:  dist\HandGalaxySetup.exe   (single portable file)
#
# Usage:
#   cd <project root>
#   .\installer\build_setup_exe.ps1
#
# To rebuild cleanly:
#   .\installer\build_setup_exe.ps1 -Clean

param(
    [switch]$Clean
)

$ErrorActionPreference = "Stop"
$root      = Split-Path -Parent $PSScriptRoot
$python    = "$root\.venv\Scripts\python.exe"
$pip       = "$root\.venv\Scripts\pip.exe"
$wizard    = "$root\installer\setup_wizard.py"
$dist_dir  = "$root\dist"
$build_dir = "$root\build_pyinstaller_setup"
$output    = "$dist_dir\HandGalaxySetup.exe"

# ── Pre-flight ──────────────────────────────────────────────────────────────
if (-not (Test-Path $python)) {
    Write-Error "Virtual environment not found at $root\.venv`nRun setup.bat first."
    exit 1
}
if (-not (Test-Path $wizard)) {
    Write-Error "setup_wizard.py not found at $wizard"
    exit 1
}

if ($Clean) {
    Write-Host "Cleaning previous build artifacts..."
    if (Test-Path $build_dir) { Remove-Item $build_dir -Recurse -Force }
    if (Test-Path $output)    { Remove-Item $output -Force }
}

# ── Install PyInstaller ─────────────────────────────────────────────────────
Write-Host "Installing PyInstaller..."
& $pip install pyinstaller --quiet
if ($LASTEXITCODE -ne 0) {
    Write-Error "PyInstaller install failed."
    exit 1
}

# ── Collect data files to bundle ────────────────────────────────────────────
# The setup.exe bundles:
#   - All Python source (src/)
#   - Assets folder structure (assets/)
#   - TouchDesigner docs (touchdesigner/)
#   - Requirements files
#   - Version file

$srcDir         = $root.Replace('\', '\\')
$escaped_root   = $root.Replace('\', '\\')

# Build datas list
$datas = @(
    "(`"$escaped_root\\src`", `"src`")",
    "(`"$escaped_root\\assets`", `"assets`")",
    "(`"$escaped_root\\touchdesigner`", `"touchdesigner`")",
    "(`"$escaped_root\\requirements.txt`", `".`")",
    "(`"$escaped_root\\requirements-virtualcam.txt`", `".`")",
    "(`"$escaped_root\\VERSION.txt`", `".`")",
    "(`"$escaped_root\\installer\\launcher_gui.py`", `"installer`")",
    "(`"$escaped_root\\installer\\launch_helper.py`", `"installer`")"
)
$datas_str = $datas -join ", "

# ── Write .spec file ─────────────────────────────────────────────────────────
$spec_content = @"
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_setup_exe.ps1

block_cipher = None

a = Analysis(
    [r'$escaped_root\installer\setup_wizard.py'],
    pathex=[r'$escaped_root\src'],
    binaries=[],
    datas=[$datas_str],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'urllib.request',
        'zipfile',
        'subprocess',
        'threading',
        'pathlib',
        'queue',
        'json',
        'shutil',
        'ctypes',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        'mediapipe', 'cv2', 'numpy', 'vosk', 'aubio', 'pyaudio',
        'pythonosc', 'matplotlib',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='HandGalaxySetup',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # No console window - wizard-only
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
"@

$spec_path = "$root\HandGalaxySetup.spec"
$spec_content | Out-File -FilePath $spec_path -Encoding UTF8

Write-Host ""
Write-Host "Building HandGalaxySetup.exe (single file, no console)..."
Write-Host "This may take 1-3 minutes."
Write-Host ""

& $python -m PyInstaller `
    --distpath "$dist_dir" `
    --workpath "$build_dir" `
    --noconfirm `
    "$spec_path"

if ($LASTEXITCODE -ne 0) {
    Write-Error "PyInstaller build failed."
    exit 1
}

# ── Clean up ─────────────────────────────────────────────────────────────────
Remove-Item $spec_path -ErrorAction SilentlyContinue
if (Test-Path $build_dir) {
    Remove-Item $build_dir -Recurse -Force -ErrorAction SilentlyContinue
}

# ── Result ────────────────────────────────────────────────────────────────────
if (Test-Path $output) {
    $size_mb = [math]::Round((Get-Item $output).Length / 1MB, 1)
    Write-Host ""
    Write-Host "================================================================="
    Write-Host "  BUILD SUCCESSFUL"
    Write-Host ""
    Write-Host "  Output:  dist\HandGalaxySetup.exe"
    Write-Host "  Size:    $size_mb MB"
    Write-Host ""
    Write-Host "  Distribute this single .exe file."
    Write-Host "  Users double-click it - no Python or dependencies needed"
    Write-Host "  on the target machine to run the installer itself."
    Write-Host "================================================================="
} else {
    Write-Error "Build failed - HandGalaxySetup.exe not found in dist\"
    exit 1
}
